version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker: 
      - image: 'cimg/base:stable'
    steps:
      - checkout
workflows:
  build:
    jobs:
      - build
  node-tests:
    jobs:
      - node/test
